const EPS=1e-12;
export function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
export function rms(samples){if(!samples?.length)return 0;let s=0;for(const v of samples)s+=v*v;return Math.sqrt(s/samples.length);}
export function dbfs(amplitude){return 20*Math.log10(Math.max(Math.abs(amplitude),EPS));}
export function peak(samples){let p=0;for(const v of samples)p=Math.max(p,Math.abs(v));return p;}
export function clippingCount(samples,threshold=.999){let n=0;for(const v of samples)if(Math.abs(v)>=threshold)n++;return n;}
export function mean(samples){if(!samples?.length)return 0;let s=0;for(const v of samples)s+=v;return s/samples.length;}
export function correlation(a,b){const n=Math.min(a?.length||0,b?.length||0);if(!n)return 0;let ma=0,mb=0;for(let i=0;i<n;i++){ma+=a[i];mb+=b[i];}ma/=n;mb/=n;let num=0,da=0,db=0;for(let i=0;i<n;i++){const x=a[i]-ma,y=b[i]-mb;num+=x*y;da+=x*x;db+=y*y;}return num/Math.sqrt(Math.max(da*db,EPS));}
export function channelBalanceDb(left,right){return dbfs(rms(left))-dbfs(rms(right));}
function goertzel(samples,sampleRate,freq){const w=2*Math.PI*freq/sampleRate;const coeff=2*Math.cos(w);let s0=0,s1=0,s2=0;for(const x of samples){s0=x+coeff*s1-s2;s2=s1;s1=s0;}const power=s1*s1+s2*s2-coeff*s1*s2;return Math.sqrt(Math.max(power,0))/Math.max(samples.length/2,1);}
export function estimateToneFrequency(samples,sampleRate,{minHz=20,maxHz=20000,coarseStepHz=1}={}){
  if(!samples?.length||sampleRate<=0)return NaN;
  const usable=samples.length>sampleRate*2? samples.subarray(0,Math.floor(sampleRate*2)):samples;
  let best=minHz,bestMag=-1;
  for(let f=minHz;f<=maxHz;f+=coarseStepHz){const m=goertzel(usable,sampleRate,f);if(m>bestMag){bestMag=m;best=f;}}
  let refined=best,bm=bestMag;const start=Math.max(minHz,best-coarseStepHz),end=Math.min(maxHz,best+coarseStepHz);for(let f=start;f<=end;f+=.1){const m=goertzel(usable,sampleRate,f);if(m>bm){bm=m;refined=f;}}
  return refined;
}
export function speedFromReferenceTone(samples,sampleRate,{referenceHz=1000,nominalRpm=33.333333,minHz,maxHz}={}){
  const span=Math.max(referenceHz*.15,25);const measuredHz=estimateToneFrequency(samples,sampleRate,{minHz:minHz??referenceHz-span,maxHz:maxHz??referenceHz+span,coarseStepHz:.5});const ratio=measuredHz/referenceHz;return {measuredHz,referenceHz,pitchPercent:(ratio-1)*100,rpm:nominalRpm*ratio,speedErrorPercent:(ratio-1)*100};
}
export function humMetrics(samples,sampleRate){const m50=goertzel(samples,sampleRate,50),m60=goertzel(samples,sampleRate,60);const mainsHz=m60>=m50?60:50;const mains=Math.max(m50,m60),alternate=Math.min(m50,m60);let harmonic=0;for(let k=2;k<=5;k++)harmonic+=goertzel(samples,sampleRate,mainsHz*k);return {mainsHz,mainsDb:dbfs(mains),alternateDb:dbfs(alternate),harmonicFamilyDb:dbfs(harmonic/4)};}
export function scopeMetrics(left,right){const lr=rms(left),rr=rms(right),corr=correlation(left,right);const ratio=Math.min(lr,rr)/Math.max(lr,rr,EPS);return {leftDb:dbfs(lr),rightDb:dbfs(rr),balanceDb:channelBalanceDb(left,right),correlation:corr,circularity:clamp(ratio*(1-Math.abs(corr)),0,1),polarity: corr < -.75 ? 'inverted' : corr > .75 ? 'correlated' : 'quadrature_or_program'};}
export function detectTransients(samples,sampleRate,{thresholdDb=18,refractoryMs=8}={}){if(!samples?.length)return [];const window=Math.max(16,Math.floor(sampleRate*.004)),refractory=Math.floor(sampleRate*refractoryMs/1000);const abs=new Float32Array(samples.length);for(let i=0;i<samples.length;i++)abs[i]=Math.abs(samples[i]);let baseline=0;for(let i=0;i<Math.min(samples.length,window*4);i++)baseline+=abs[i];baseline/=Math.max(1,Math.min(samples.length,window*4));const ratio=Math.pow(10,thresholdDb/20);let last=-refractory,run=0;const events=[];for(let i=0;i<samples.length;i++){run+=abs[i];if(i>=window)run-=abs[i-window];const local=run/Math.min(i+1,window);const floor=Math.max(baseline*.35,1e-5);if(i-last>=refractory && abs[i] > Math.max(local*ratio,floor*ratio)){const sev=clamp((dbfs(abs[i])-dbfs(Math.max(local,floor)))/36,0,1);events.push({sample:i,timeSec:i/sampleRate,severity:sev,confidence:clamp(.55+sev*.4,0,1)});last=i;}baseline=baseline*.9995+abs[i]*.0005;}return events;}
export function recurrenceMetrics(events,{sampleRate=48000,tolerance=.08}={}){if(!events||events.length<3)return {periodSec:null,confidence:0,repetitions:0};const times=events.map(e=>e.timeSec ?? e.sample/sampleRate).sort((a,b)=>a-b);const diffs=[];for(let i=1;i<times.length;i++)diffs.push(times[i]-times[i-1]);diffs.sort((a,b)=>a-b);const med=diffs[Math.floor(diffs.length/2)];const matches=diffs.filter(d=>Math.abs(d-med)<=Math.max(.01,med*tolerance)).length;return {periodSec:med,confidence:matches/Math.max(1,diffs.length),repetitions:matches+1};}
export function lowBandEnergyDb(samples,sampleRate,maxHz=30){if(!samples?.length)return -240;let sum=0,count=0;for(let f=5;f<=maxHz;f+=5){const a=goertzel(samples,sampleRate,f);sum+=a*a;count++;}return dbfs(Math.sqrt(sum/Math.max(1,count)));}
export function conditionScore({transientDensityPerMin=0,humDb=-100,rumbleDb=-100,repeatingSeverity=0,clipping=0}={}){let score=100;score-=Math.min(28,transientDensityPerMin*.7);score-=Math.max(0,Math.min(20,(humDb+65)*.8));score-=Math.max(0,Math.min(16,(rumbleDb+55)*.65));score-=clamp(repeatingSeverity,0,1)*26;score-=Math.min(20,clipping*.25);return Math.round(clamp(score,0,100));}
export function normalizeMeasurement({metricId,label,value,unit,origin='measured',confidence=1,uncertainty=null,referenceLow=null,referenceHigh=null,qualityFlags=[]}){return {metricId,label,value,unit,origin,confidence,uncertainty,referenceLow,referenceHigh,qualityFlags};}
export function quickDiagnostic({left,right,sampleRate}){const sm=scopeMetrics(left,right);const humL=humMetrics(left,sampleRate),humR=humMetrics(right,sampleRate);const clipL=clippingCount(left),clipR=clippingCount(right);const measurements=[normalizeMeasurement({metricId:'left_level_dbfs',label:'Left level',value:sm.leftDb,unit:'dBFS'}),normalizeMeasurement({metricId:'right_level_dbfs',label:'Right level',value:sm.rightDb,unit:'dBFS'}),normalizeMeasurement({metricId:'channel_balance_db',label:'Channel balance L-R',value:sm.balanceDb,unit:'dB'}),normalizeMeasurement({metricId:'correlation',label:'Stereo correlation',value:sm.correlation,unit:''}),normalizeMeasurement({metricId:'left_hum_dbfs',label:`Left ${humL.mainsHz} Hz hum`,value:humL.mainsDb,unit:'dBFS'}),normalizeMeasurement({metricId:'right_hum_dbfs',label:`Right ${humR.mainsHz} Hz hum`,value:humR.mainsDb,unit:'dBFS'}),normalizeMeasurement({metricId:'clipped_samples',label:'Clipped samples',value:clipL+clipR,unit:'samples'})];const findings=[];if(Math.abs(sm.balanceDb)>=1)findings.push({code:'CHANNEL_IMBALANCE',title:'Channel imbalance',detail:`Left/right level differs by ${Math.abs(sm.balanceDb).toFixed(2)} dB.`,severity:Math.abs(sm.balanceDb)>=3?'warning':'review',confidence:.9,possibleCauses:['cartridge alignment or wear','headshell/contact resistance','cable or connector loss','mixer/interface gain mismatch'],isolationTests:['swap left/right signal path','repeat with known reference source','inspect and clean cartridge/headshell contacts']});if(sm.correlation<-.75)findings.push({code:'POLARITY_INVERSION',title:'Possible polarity inversion',detail:'Strong negative correlation was measured between channels.',severity:'warning',confidence:.95,possibleCauses:['reversed cartridge lead','inverted cable or processing path'],isolationTests:['check cartridge lead colors','repeat with mono reference signal']});if(clipL+clipR>0)findings.push({code:'CLIPPING',title:'Input clipping detected',detail:`${clipL+clipR} samples reached the clipping threshold.`,severity:'warning',confidence:1,possibleCauses:['interface gain too high','upstream overload'],isolationTests:['reduce input gain','repeat capture']});if(Math.max(humL.mainsDb,humR.mainsDb)>-45)findings.push({code:'MAINS_HUM',title:'Elevated mains hum',detail:`Dominant mains-family component measured near ${humL.mainsDb>=humR.mainsDb?humL.mainsHz:humR.mainsHz} Hz.`,severity:'review',confidence:.85,possibleCauses:['ground loop','missing turntable ground','cable shielding','nearby power source'],isolationTests:['compare with source disconnected','verify turntable ground','move signal cable away from AC wiring']});return {measurements,findings,summary:{balanceDb:sm.balanceDb,correlation:sm.correlation,clipping:clipL+clipR}};}
export function analyzeVinylSide({left,right,sampleRate}){const n=Math.min(left.length,right.length),mono=new Float32Array(n);for(let i=0;i<n;i++)mono[i]=(left[i]+right[i])*.5;const events=detectTransients(mono,sampleRate,{thresholdDb:14,refractoryMs:12});const recurrence=recurrenceMetrics(events,{sampleRate});const duration=n/sampleRate;const transientDensityPerMin=events.length/Math.max(duration/60,1/60);const hum=humMetrics(mono,sampleRate);const rumbleDb=lowBandEnergyDb(mono,sampleRate);const clipping=clippingCount(left)+clippingCount(right);const score=conditionScore({transientDensityPerMin,humDb:hum.mainsDb,rumbleDb,repeatingSeverity:recurrence.confidence,clipping});return {events,recurrence,durationSec:duration,transientDensityPerMin,humDb:hum.mainsDb,rumbleDb,clipping,conditionScore:score,liveReadiness:score>=85?'ready':score>=65?'review':'service'};}
export function compareRuns(a,b){const map=new Map((b?.measurements||[]).map(m=>[m.metricId,m]));return (a?.measurements||[]).flatMap(m=>{const other=map.get(m.metricId);if(!other||typeof m.value!=='number'||typeof other.value!=='number'||m.unit!==other.unit)return [];return [{metricId:m.metricId,label:m.label||other.label,unit:m.unit,a:m.value,b:other.value,delta:other.value-m.value}];});}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
export function buildHtmlReport({title='DeckChek Report',device='',createdAt=new Date().toISOString(),measurements=[],findings=[],notes=''}){const rows=measurements.map(m=>`<tr><td>${esc(m.label||m.metricId)}</td><td>${typeof m.value==='number'?Number(m.value).toFixed(3):esc(m.value)}</td><td>${esc(m.unit)}</td><td>${esc(m.origin||'measured')}</td><td>${m.confidence==null?'':Math.round(m.confidence*100)+'%'}</td></tr>`).join('');const fs=findings.map(f=>`<li><strong>${esc(f.title)}</strong> — ${esc(f.detail)} <small>${esc(f.severity||'')}</small></li>`).join('');return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>body{font-family:system-ui,sans-serif;margin:40px;color:#18202a}table{border-collapse:collapse;width:100%}th,td{border-bottom:1px solid #ccd3da;padding:8px;text-align:left}small{color:#667}</style></head><body><h1>${esc(title)}</h1><p><b>Device:</b> ${esc(device)}</p><p><b>Created:</b> ${esc(createdAt)}</p><h2>Measurements</h2><table><thead><tr><th>Metric</th><th>Value</th><th>Unit</th><th>Origin</th><th>Confidence</th></tr></thead><tbody>${rows}</tbody></table><h2>Findings</h2><ul>${fs||'<li>No findings.</li>'}</ul>${notes?`<h2>Notes</h2><p>${esc(notes)}</p>`:''}<p><small>DeckChek measurements are evidence records. Diagnostic findings may list multiple possible causes and should be isolated with repeatable tests.</small></p></body></html>`;}
