// FS-03 print host. Runs inside the hidden PDF window only (app/print-host.html).
// The report HTML is generated by DeckChek with every user string escaped; this file
// still strips anything active before adopting it, so a bug upstream cannot run script
// or load remote content in the print window. No IPC is used: Rust polls `state`.

const REMOVE_SELECTOR = 'script, iframe, frame, frameset, object, embed, base, meta[http-equiv], form, noscript, template';
const URL_ATTRS = ['src', 'href', 'xlink:href', 'srcset', 'action', 'formaction', 'poster', 'background'];
const ASSET_TIMEOUT_MS = 5000;

/** True for same-origin relative URLs and inline data: images; false for anything remote or active. */
export function isSafeUrl(value, { allowDataImage = false } = {}) {
  const v = String(value || '').trim();
  if (v === '' || v.startsWith('#')) return true;
  if (allowDataImage && /^data:image\/(png|jpeg|gif|webp|svg\+xml);/i.test(v)) return true;
  if (v.startsWith('//')) return false;
  // Any explicit scheme (http:, javascript:, file:, data: …) is refused.
  return !/^[a-z][a-z0-9+.-]*:/i.test(v);
}

/** Removes active content, event handlers and remote references from a parsed document, in place. */
export function sanitizeDocument(doc) {
  doc.querySelectorAll(REMOVE_SELECTOR).forEach((el) => el.remove());
  doc.querySelectorAll('link').forEach((el) => {
    const rel = (el.getAttribute('rel') || '').toLowerCase().split(/\s+/);
    if (!rel.includes('stylesheet') || !isSafeUrl(el.getAttribute('href'))) el.remove();
  });
  doc.querySelectorAll('*').forEach((el) => {
    for (const attr of Array.from(el.attributes)) {
      const name = attr.name.toLowerCase();
      if (name.startsWith('on')) {
        el.removeAttribute(attr.name);
      } else if (URL_ATTRS.includes(name)) {
        const allowDataImage = el.localName === 'img' || el.localName === 'image';
        if (!isSafeUrl(attr.value, { allowDataImage })) el.removeAttribute(attr.name);
      } else if (name === 'style' && /url\s*\(|expression\s*\(/i.test(attr.value)) {
        el.removeAttribute(attr.name);
      }
    }
  });
  doc.querySelectorAll('style').forEach((el) => {
    // @import and url() could fetch remote resources; reports never need them.
    if (/@import|url\s*\(\s*['"]?\s*(?:[a-z][a-z0-9+.-]*:|\/\/)/i.test(el.textContent || '')) {
      el.textContent = (el.textContent || '')
        .replace(/@import[^;]*;?/gi, '')
        .replace(/url\s*\(\s*['"]?\s*(?:[a-z][a-z0-9+.-]*:|\/\/)[^)]*\)/gi, 'none');
    }
  });
  return doc;
}

function withTimeout(promise, ms) {
  return Promise.race([promise, new Promise((resolve) => setTimeout(resolve, ms))]);
}

function waitForImages(root) {
  const pending = Array.from(root.querySelectorAll('img')).filter((img) => !img.complete);
  return Promise.all(pending.map((img) => new Promise((resolve) => {
    img.addEventListener('load', resolve, { once: true });
    img.addEventListener('error', resolve, { once: true });
  })));
}

function adopt(doc, document) {
  document.querySelectorAll('[data-print-content]').forEach((el) => el.remove());
  for (const el of Array.from(doc.head.querySelectorAll('style, link'))) {
    const copy = document.importNode(el, true);
    copy.setAttribute('data-print-content', '');
    document.head.appendChild(copy);
  }
  document.title = doc.title || 'DeckChek report';
  const lang = doc.documentElement.getAttribute('lang');
  if (lang) document.documentElement.setAttribute('lang', lang);
  // Print output is always light (FS-03 AC-4), whatever the report markup says.
  document.documentElement.setAttribute('data-theme', 'light');
  document.body.replaceWith(document.importNode(doc.body, true));
}

export function createPrintHost(win) {
  const host = { state: 'idle', error: null, version: 1, render };
  function render(html) {
    host.state = 'loading';
    host.error = null;
    try {
      if (typeof html !== 'string' || html.length === 0) throw new Error('empty report');
      const doc = new win.DOMParser().parseFromString(html, 'text/html');
      adopt(sanitizeDocument(doc), win.document);
    } catch (e) {
      host.state = 'error';
      host.error = String((e && e.message) || e).slice(0, 200);
      return host.state;
    }
    const fonts = win.document.fonts && win.document.fonts.ready ? win.document.fonts.ready : Promise.resolve();
    withTimeout(Promise.all([fonts, waitForImages(win.document)]), ASSET_TIMEOUT_MS)
      // One macrotask so layout settles; rAF is not used because it stalls in hidden windows.
      .then(() => new Promise((resolve) => setTimeout(resolve, 0)))
      .then(() => { host.state = 'ready'; }, (e) => {
        host.state = 'error';
        host.error = String((e && e.message) || e).slice(0, 200);
      });
    return host.state;
  }
  return host;
}

if (typeof window !== 'undefined' && typeof document !== 'undefined') {
  window.__dcPrintHost = createPrintHost(window);
}
