// Options and Help menu entries for support (FS-02, FS-07). The Options and Help dialogs are
// generated by ui-assistance.js and re-rendered on open, so entries are appended after each open.
// All outbound links go through the FS-07 helper (allowlist, confirm, desktop command).

import { h } from './dom.js';
import { icon } from './icons.js';
import { toast } from './live.js';
import { ISSUE_REPO } from '../diagnostics-bundle.js';
import { openExternal, linkConfirmDialog } from '../external-links.js';
import { openExperimentalDialog } from './screens/experimental.js';

export const DIAGNOSTICS_EVENT = 'deckchek:diagnostics';
export const EXPERIMENTAL_EVENT = 'deckchek:experimental';

export const SUPPORT_LINKS = Object.freeze([
  { id: 'issues', label: 'Report an issue (GitHub)', url: `https://github.com/${ISSUE_REPO}/issues` },
  { id: 'releases', label: 'Releases and updates (GitHub)', url: `https://github.com/${ISSUE_REPO}/releases` },
]);

// Manufacturer support pages; every host is on the FS-07 allowlist (tests/menus.test.mjs asserts it).
export const MANUFACTURER_LINKS = Object.freeze([
  { id: 'pioneer', label: 'Pioneer DJ support', url: 'https://www.pioneerdj.com/en/support/' },
  { id: 'serato', label: 'Serato support', url: 'https://support.serato.com/' },
  { id: 'ni', label: 'Native Instruments support', url: 'https://support.native-instruments.com/' },
  { id: 'rekordbox', label: 'rekordbox support', url: 'https://rekordbox.com/en/support/' },
]);

/** Pure description of the entries, used for rendering and tests. */
export function supportMenuModel() {
  return {
    options: [
      { id: 'diagnostics', label: 'Create diagnostics bundle…', kind: 'event', event: DIAGNOSTICS_EVENT },
      { id: 'experimental', label: 'Experimental features…', kind: 'event', event: EXPERIMENTAL_EVENT },
    ],
    help: [
      { id: 'diagnostics', label: 'Create diagnostics bundle…', kind: 'event', event: DIAGNOSTICS_EVENT },
      ...SUPPORT_LINKS.map(l => ({ ...l, kind: 'link' })),
      ...MANUFACTURER_LINKS.map(l => ({ ...l, kind: 'link', group: 'manufacturer' })),
    ],
  };
}

function run(entry, dialog) {
  // The support dialog ignores the event while another modal is open, so close ours first.
  if (dialog?.open) dialog.close();
  if (entry.event === EXPERIMENTAL_EVENT) openExperimentalDialog();
  else if (entry.kind === 'event') globalThis.dispatchEvent(new CustomEvent(entry.event));
  else openExternal(entry.url, { toast, confirm: linkConfirmDialog });
}

function buildBox(entries, title, intro, dialog) {
  const btn = e => h('button', { type: 'button', class: 'btn btn-secondary btn-sm', 'data-support-id': e.id, onclick: () => run(e, dialog) },
    e.kind === 'link' ? h('span', { 'aria-hidden': 'true', html: icon('external', { size: 14 }) }) : null, ` ${e.label}`);
  const main = entries.filter(e => e.group !== 'manufacturer');
  const makers = entries.filter(e => e.group === 'manufacturer');
  return h('fieldset', { class: 'support-entry', 'data-support-entry': '' },
    h('legend', { text: title }),
    h('p', { text: intro }),
    h('div', { class: 'support-entry-actions' }, main.map(btn)),
    makers.length ? h('p', { class: 'small muted', text: 'Manufacturer support pages (open in your browser):' }) : null,
    makers.length ? h('div', { class: 'support-entry-actions' }, makers.map(btn)) : null);
}

/** Appends the Support box to a dialog's body once per render. Returns true when added. */
export function addSupportEntries(dialog, which, model = supportMenuModel()) {
  const target = dialog?.querySelector?.('.cdl-help-body');
  if (!target || target.querySelector('[data-support-entry]')) return false;
  target.append(which === 'options'
    ? buildBox(model.options, 'Support', 'Create a diagnostics bundle to share when something goes wrong. It contains no audio and nothing is sent automatically (Ctrl+Shift+D). Experimental features switches the unfinished screens on or off.', dialog)
    : buildBox(model.help, 'Support and links', 'Get help, report a problem or check for a new release.', dialog));
  return true;
}

let installed = false;
/** Called once from the shell. Click handlers run after ui-assistance has rendered the dialog. */
export function installSupportMenus(doc = globalThis.document) {
  if (installed || !doc) return;
  installed = true;
  doc.addEventListener('click', event => {
    const which = event.target.closest?.('#cdlOptionsBtn') ? 'options' : event.target.closest?.('#helpBtn, #cdlHelpBtn') ? 'help' : null;
    if (!which) return;
    setTimeout(() => addSupportEntries(doc.getElementById(which === 'options' ? 'cdlOptionsDialog' : doc.getElementById('helpDialog') ? 'helpDialog' : 'cdlHelpDialog'), which), 0);
  }, true); // capture: the help button's own handler stops propagation
}
