use rusqlite::{params, Connection};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::ops::{Deref, DerefMut};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{PoisonError, RwLock, RwLockReadGuard};
use std::{fs, path::{Path, PathBuf}};
use tauri::{AppHandle, Manager};

// Ordered schema migrations `MIGRATIONS: &[(i64, &str)]`, generated by
// build.rs from every `database/migrations/NNNN_name.sql` (FS-00 §4.2). Each
// runs once, inside a transaction that also records it in `schema_migration`.
include!(concat!(env!("OUT_DIR"), "/migrations.rs"));

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PersistMeasurement {
    pub metric_id: String,
    pub label: Option<String>,
    pub value: f64,
    pub unit: String,
    pub origin: Option<String>,
    pub confidence: Option<f64>,
    pub uncertainty: Option<f64>,
    pub quality_flags: Option<Vec<String>>,
}

#[derive(Debug, Default, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PersistFinding {
    pub code: String,
    pub title: String,
    pub detail: String,
    pub severity: String,
    pub confidence: Option<f64>,
    pub possible_causes: Option<Vec<String>>,
    pub isolation_tests: Option<Vec<String>>,
    /// Alternative explanations (stored in hypothesis.alternatives_json).
    #[serde(default)]
    pub alternatives: Option<Vec<String>>,
    /// Metric ids of measurements that support this finding.
    #[serde(default)]
    pub supported_by: Option<Vec<String>>,
    /// Metric ids of measurements that contradict this finding.
    #[serde(default)]
    pub contradicted_by: Option<Vec<String>>,
    /// Optional explicit hypothesis status; derived when absent.
    #[serde(default)]
    pub status: Option<String>,
}

#[derive(Debug, Default, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PersistRun {
    pub id: String,
    pub device_id: Option<String>,
    pub test: String,
    pub created_at: String,
    pub source_file: Option<String>,
    pub sample_rate: Option<u32>,
    pub channels: Option<u16>,
    pub measurements: Vec<PersistMeasurement>,
    pub findings: Vec<PersistFinding>,
    pub score: Option<f64>,
    /// Workflow/mode; stored as session.session_type (default "diagnostic").
    #[serde(default)]
    pub session_type: Option<String>,
    #[serde(default)]
    pub workflow: Option<String>,
    /// Real capture start (UTC ISO). Absent on payloads from older builds: the
    /// session then spans `created_at` only, exactly as before.
    #[serde(default)]
    pub started_at: Option<String>,
    /// Real capture end (UTC ISO); defaults to `created_at` when timing is given.
    #[serde(default)]
    pub ended_at: Option<String>,
    /// Captured audio length in seconds; derives `started_at` when that is absent.
    #[serde(default)]
    pub duration_sec: Option<f64>,
    /// `live` (an input capture, the stylus was playing) or `file` (an analysed recording).
    #[serde(default)]
    pub capture_kind: Option<String>,
    /// Asset the run was recorded with (stored in the config snapshot).
    #[serde(default)]
    pub asset_id: Option<String>,
    /// Existing setup the run used (session.setup_id); unknown ids are rejected.
    #[serde(default)]
    pub setup_id: Option<String>,
}

/// Longest capture span a run may claim (24 h).
pub const MAX_CAPTURE_SEC: f64 = 86_400.0;
pub const CAPTURE_KINDS: &[&str] = &["live", "file"];

/// Resolved capture timing for a run: (started_at, ended_at, duration_sec).
/// Legacy payloads (no timing fields) keep started_at == ended_at == created_at.
fn capture_span(conn: &Connection, run: &PersistRun) -> Result<(String, String, Option<f64>), String> {
    use crate::usage::valid_timestamp;
    if let Some(k) = &run.capture_kind {
        if !CAPTURE_KINDS.contains(&k.as_str()) {
            return Err(format!("captureKind must be one of {}", CAPTURE_KINDS.join(", ")));
        }
    }
    if let Some(d) = run.duration_sec {
        if !d.is_finite() || !(0.0..=MAX_CAPTURE_SEC).contains(&d) {
            return Err(format!("durationSec must be between 0 and {MAX_CAPTURE_SEC}"));
        }
    }
    if run.started_at.is_none() && run.ended_at.is_none() && run.duration_sec.is_none() {
        return Ok((run.created_at.clone(), run.created_at.clone(), None));
    }
    let ended = run.ended_at.clone().unwrap_or_else(|| run.created_at.clone());
    if !valid_timestamp(&ended) {
        return Err(format!("endedAt must be a UTC ISO timestamp, got '{ended}'"));
    }
    let started = match (&run.started_at, run.duration_sec) {
        (Some(s), _) => {
            if !valid_timestamp(s) {
                return Err(format!("startedAt must be a UTC ISO timestamp, got '{s}'"));
            }
            s.clone()
        }
        (None, Some(d)) => conn
            .query_row("SELECT strftime('%Y-%m-%dT%H:%M:%fZ', ?1, ?2)", params![ended, format!("-{d:.3} seconds")], |r| r.get::<_, String>(0))
            .map_err(e2s)?,
        (None, None) => ended.clone(),
    };
    let span: f64 = conn
        .query_row("SELECT (julianday(?2) - julianday(?1)) * 86400.0", params![started, ended], |r| r.get(0))
        .map_err(e2s)?;
    if span < -0.0005 {
        return Err("startedAt must not be after endedAt".into());
    }
    if span > MAX_CAPTURE_SEC + 1.0 {
        return Err(format!("a capture may span at most {MAX_CAPTURE_SEC} s"));
    }
    Ok((started, ended, Some(run.duration_sec.unwrap_or_else(|| (span.max(0.0) * 1000.0).round() / 1000.0))))
}

pub fn database_path(app: &AppHandle) -> Result<PathBuf, String> {
    let dir = app.path().app_data_dir().map_err(|e| e.to_string())?;
    fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    Ok(dir.join("deckchek.sqlite3"))
}

/// Process-wide connection gate (FS-00 §4.2). Every [`open_database`]
/// connection holds a read guard for its lifetime; whole-file operations such
/// as FS-08 restore take the write guard so no connection is open meanwhile.
static GATE: RwLock<()> = RwLock::new(());

pub fn gate() -> &'static RwLock<()> {
    &GATE
}

/// A migrated connection that keeps the [`gate`] read guard until dropped.
/// Derefs to [`Connection`], so it is used exactly like one.
pub struct DbConn {
    // Field order matters: the connection closes before the guard is released.
    conn: Connection,
    _gate: RwLockReadGuard<'static, ()>,
}

impl Deref for DbConn {
    type Target = Connection;
    fn deref(&self) -> &Connection {
        &self.conn
    }
}

impl DerefMut for DbConn {
    fn deref_mut(&mut self) -> &mut Connection {
        &mut self.conn
    }
}

pub fn open_database(path: &Path) -> Result<DbConn, String> {
    let guard = gate().read().unwrap_or_else(PoisonError::into_inner);
    let conn = Connection::open(path).map_err(|e| e.to_string())?;
    conn.execute_batch("PRAGMA foreign_keys=ON;").map_err(|e| e.to_string())?;
    apply_migrations(&conn)?;
    crate::catalog::seed_if_empty(&conn)?;
    Ok(DbConn { conn, _gate: guard })
}

/// Apply every migration in [`MIGRATIONS`] that is not yet recorded, in order.
/// Idempotent: re-running is a no-op. Each migration's SQL and its
/// `schema_migration` row commit in one transaction, so a crash can never leave
/// a migration applied but unrecorded (FS-00 AC-2). A failing migration is
/// rolled back and stops the run so later migrations never apply on top of it.
pub fn apply_migrations(conn: &Connection) -> Result<(), String> {
    apply_migration_list(conn, MIGRATIONS, None)
}

fn is_applied(conn: &Connection, version: i64) -> Result<bool, String> {
    conn.query_row("SELECT COUNT(*) FROM schema_migration WHERE version = ?1", [version], |r| r.get::<_, i64>(0))
        .map(|n| n > 0)
        .map_err(|e| e.to_string())
}

/// `fail_after_sql` injects an error after that version's SQL ran but before
/// its transaction commits (tests only pass `Some`).
fn apply_migration_list(conn: &Connection, migrations: &[(i64, &str)], fail_after_sql: Option<i64>) -> Result<(), String> {
    conn.execute_batch("CREATE TABLE IF NOT EXISTS schema_migration (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL, app_version TEXT);")
        .map_err(|e| e.to_string())?;
    for &(version, sql) in migrations {
        if is_applied(conn, version)? {
            continue;
        }
        // IMMEDIATE takes the write lock up front; the re-check inside it stops a
        // second connection that raced past the check above from re-running it.
        conn.execute_batch("BEGIN IMMEDIATE;").map_err(|e| format!("migration {version} failed: {e}"))?;
        let step = (|| -> Result<(), String> {
            if is_applied(conn, version)? {
                return Ok(());
            }
            conn.execute_batch(sql).map_err(|e| e.to_string())?;
            if fail_after_sql == Some(version) {
                return Err("injected failure after migration SQL".into());
            }
            conn.execute(
                "INSERT OR IGNORE INTO schema_migration(version, applied_at, app_version) VALUES (?1, CURRENT_TIMESTAMP, ?2)",
                params![version, env!("CARGO_PKG_VERSION")],
            )
            .map_err(|e| e.to_string())?;
            Ok(())
        })()
        .and_then(|()| conn.execute_batch("COMMIT;").map_err(|e| e.to_string()));
        if let Err(e) = step {
            let _ = conn.execute_batch("ROLLBACK;");
            return Err(format!("migration {version} failed: {e}"));
        }
    }
    Ok(())
}

/// Versions recorded in `schema_migration` below the seed marker, ascending.
#[cfg(test)]
pub fn applied_migrations(conn: &Connection) -> Result<Vec<i64>, String> {
    let mut stmt = conn.prepare("SELECT version FROM schema_migration WHERE version < 1000 ORDER BY version").map_err(|e| e.to_string())?;
    let rows = stmt.query_map([], |r| r.get(0)).map_err(|e| e.to_string())?;
    rows.collect::<rusqlite::Result<Vec<i64>>>().map_err(|e| e.to_string())
}

static ID_COUNTER: AtomicU64 = AtomicU64::new(0);

/// UUID-v4-shaped unique id (std-only; not cryptographic).
pub fn new_id() -> String {
    use std::collections::hash_map::RandomState;
    use std::hash::{BuildHasher, Hasher};
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    let n = ID_COUNTER.fetch_add(1, Ordering::Relaxed);
    let mut h1 = RandomState::new().build_hasher();
    h1.write_u128(nanos);
    h1.write_u64(n);
    let mut h2 = RandomState::new().build_hasher();
    h2.write_u64(h1.finish());
    h2.write_u64(n);
    let (a, b) = (h1.finish(), h2.finish());
    format!(
        "{:08x}-{:04x}-4{:03x}-{:04x}-{:012x}",
        (a >> 32) as u32,
        (a >> 16) as u16,
        (a & 0xfff) as u16,
        ((b >> 48) as u16 & 0x3fff) | 0x8000,
        b & 0xffff_ffff_ffff
    )
}

pub fn now_iso(conn: &Connection) -> Result<String, String> {
    conn.query_row("SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now')", [], |r| r.get(0)).map_err(|e| e.to_string())
}

fn e2s(e: rusqlite::Error) -> String {
    e.to_string()
}

pub fn persist_run(conn: &mut Connection, run: &PersistRun) -> Result<(), String> {
    let (started_at, ended_at, duration_sec) = capture_span(conn, run)?;
    let setup_id = run.setup_id.as_deref().map(str::trim).filter(|s| !s.is_empty());
    let tx = conn.transaction().map_err(e2s)?;
    if let Some(setup) = setup_id {
        let known: i64 = tx.query_row("SELECT COUNT(*) FROM setup WHERE id = ?1", [setup], |r| r.get(0)).map_err(e2s)?;
        if known == 0 {
            return Err(format!("unknown setup '{setup}'"));
        }
    }
    let mut config = json!({
        "test": run.test,
        "sourceFile": run.source_file,
        "sampleRate": run.sample_rate,
        "channels": run.channels,
        "score": run.score,
        "deviceId": run.device_id,
    });
    // Timing keys only on payloads that carry them, so older rows and payloads are byte-identical.
    if let Some(d) = duration_sec {
        config["durationSec"] = json!(d);
    }
    if let Some(k) = &run.capture_kind {
        config["captureKind"] = json!(k);
    }
    if let Some(a) = run.asset_id.as_deref().filter(|a| !a.trim().is_empty()) {
        config["assetId"] = json!(a);
    }
    let config = config.to_string();
    let session_type = run.session_type.as_deref().or(run.workflow.as_deref()).filter(|s| !s.trim().is_empty()).unwrap_or("diagnostic");

    // Upsert in place: REPLACE would delete the old row first and, with foreign_keys=ON, cascade away /
    // null out every other feature's rows that point at this session (scan alignments, hours, wear...).
    tx.execute(
        "INSERT INTO session (id, session_type, setup_id, started_at, ended_at, app_version, schema_version, status, context_profile, operator_notes, session_quality, config_snapshot_json) VALUES (?1, ?2, ?8, ?3, ?9, ?4, 1, 'completed', ?5, NULL, ?6, ?7) \
         ON CONFLICT(id) DO UPDATE SET session_type = excluded.session_type, setup_id = excluded.setup_id, started_at = excluded.started_at, ended_at = excluded.ended_at, app_version = excluded.app_version, schema_version = excluded.schema_version, status = excluded.status, context_profile = excluded.context_profile, session_quality = excluded.session_quality, config_snapshot_json = excluded.config_snapshot_json",
        params![run.id, session_type, started_at, env!("CARGO_PKG_VERSION"), run.test, run.score.map(|v| v / 100.0), config, setup_id, ended_at],
    ).map_err(e2s)?;
    // The run's own derived rows are rewritten below; clear the old ones explicitly (link tables cascade
    // from these rows, and nothing else references them).
    for table in ["hypothesis", "evidence", "measurement"] {
        tx.execute(&format!("DELETE FROM {table} WHERE session_id = ?1"), [&run.id]).map_err(e2s)?;
    }

    let mut measurement_ids: std::collections::HashMap<&str, String> = std::collections::HashMap::new();
    for m in &run.measurements {
        let method_id = format!("method:{}:1", m.metric_id);
        let description = m.label.as_deref().unwrap_or(&m.metric_id);
        tx.execute(
            "INSERT OR IGNORE INTO analysis_method (id, key, version, description, parameters_json, created_at) VALUES (?1, ?2, 1, ?3, '{}', CURRENT_TIMESTAMP)",
            params![method_id, m.metric_id, description],
        ).map_err(e2s)?;

        let measurement_id = format!("{}:{}", run.id, m.metric_id);
        let flags = serde_json::to_string(m.quality_flags.as_deref().unwrap_or(&[])).map_err(|e| e.to_string())?;
        tx.execute(
            "INSERT OR REPLACE INTO measurement (id, session_id, capture_id, method_id, metric_key, state, numeric_value, text_value, unit, channel_scope, confidence, uncertainty, quality_flags_json, created_at) VALUES (?1, ?2, NULL, ?3, ?4, ?5, ?6, NULL, ?7, NULL, ?8, ?9, ?10, ?11)",
            params![measurement_id, run.id, method_id, m.metric_id, m.origin.as_deref().unwrap_or("measured"), m.value, m.unit, m.confidence, m.uncertainty, flags, run.created_at],
        ).map_err(e2s)?;
        measurement_ids.insert(m.metric_id.as_str(), measurement_id);
    }

    for (index, f) in run.findings.iter().enumerate() {
        let confidence = f.confidence.unwrap_or(0.5).clamp(0.0, 1.0);
        let evidence_id = format!("{}:finding:{}:{}", run.id, index, f.code);
        let features = json!({
            "code": f.code,
            "possibleCauses": f.possible_causes,
            "isolationTests": f.isolation_tests,
        }).to_string();
        let summary = format!("{}: {}", f.title, f.detail);
        tx.execute(
            "INSERT OR REPLACE INTO evidence (id, session_id, evidence_type, severity, confidence, summary, features_json, created_at) VALUES (?1, ?2, 'diagnostic_finding', ?3, ?4, ?5, ?6, ?7)",
            params![evidence_id, run.id, f.severity, confidence, summary, features, run.created_at],
        ).map_err(e2s)?;

        for metric in f.supported_by.iter().flatten() {
            if let Some(mid) = measurement_ids.get(metric.as_str()) {
                tx.execute("INSERT OR IGNORE INTO evidence_measurement (evidence_id, measurement_id) VALUES (?1, ?2)", params![evidence_id, mid]).map_err(e2s)?;
            }
        }

        let contra: Vec<&String> = f.contradicted_by.iter().flatten().filter(|m| measurement_ids.contains_key(m.as_str())).collect();
        let status = f.status.clone().unwrap_or_else(|| if contra.is_empty() { "supported".into() } else { "contested".into() });
        let hypothesis_id = format!("{}:hyp:{}:{}", run.id, index, f.code);
        let alternatives = serde_json::to_string(f.alternatives.as_deref().or(f.possible_causes.as_deref()).unwrap_or(&[])).map_err(|e| e.to_string())?;
        let isolation = serde_json::to_string(f.isolation_tests.as_deref().unwrap_or(&[])).map_err(|e| e.to_string())?;
        tx.execute(
            "INSERT OR REPLACE INTO hypothesis (id, session_id, hypothesis_key, status, confidence, severity, summary, reasoning_version, alternatives_json, isolation_tests_json, created_at, updated_at) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, 1, ?8, ?9, ?10, ?10)",
            params![hypothesis_id, run.id, f.code, status, confidence, f.severity, summary, alternatives, isolation, run.created_at],
        ).map_err(e2s)?;
        tx.execute(
            "INSERT OR REPLACE INTO hypothesis_support (evidence_id, hypothesis_id, weight) VALUES (?1, ?2, ?3)",
            params![evidence_id, hypothesis_id, confidence],
        ).map_err(e2s)?;

        for metric in contra {
            let mid = &measurement_ids[metric.as_str()];
            let cev = format!("{}:contra:{}:{}", run.id, index, metric);
            tx.execute(
                "INSERT OR REPLACE INTO evidence (id, session_id, evidence_type, severity, confidence, summary, features_json, created_at) VALUES (?1, ?2, 'contradicting_measurement', 'info', ?3, ?4, ?5, ?6)",
                params![cev, run.id, confidence, format!("Measurement {metric} contradicts {}", f.code), json!({"metricId": metric, "hypothesis": f.code}).to_string(), run.created_at],
            ).map_err(e2s)?;
            tx.execute("INSERT OR IGNORE INTO evidence_measurement (evidence_id, measurement_id) VALUES (?1, ?2)", params![cev, mid]).map_err(e2s)?;
            tx.execute("INSERT OR REPLACE INTO hypothesis_contradiction (evidence_id, hypothesis_id, weight) VALUES (?1, ?2, 1.0)", params![cev, hypothesis_id]).map_err(e2s)?;
        }
    }

    tx.commit().map_err(e2s)
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct RunSummary {
    pub id: String,
    pub session_type: String,
    pub test: Option<String>,
    pub started_at: String,
    pub ended_at: Option<String>,
    pub status: String,
    pub score: Option<f64>,
    pub measurement_count: i64,
    pub hypothesis_count: i64,
}

pub fn list_runs(conn: &Connection, limit: Option<u32>) -> Result<Vec<RunSummary>, String> {
    let limit = limit.unwrap_or(50).clamp(1, 500) as i64;
    let mut stmt = conn.prepare(
        "SELECT s.id, s.session_type, s.context_profile, s.started_at, s.status, s.session_quality,
                (SELECT COUNT(*) FROM measurement m WHERE m.session_id = s.id),
                (SELECT COUNT(*) FROM hypothesis h WHERE h.session_id = s.id), s.ended_at
         FROM session s ORDER BY s.started_at DESC, s.id LIMIT ?1",
    ).map_err(e2s)?;
    let rows = stmt.query_map([limit], |r| {
        Ok(RunSummary {
            id: r.get(0)?,
            session_type: r.get(1)?,
            test: r.get(2)?,
            started_at: r.get(3)?,
            ended_at: r.get(8)?,
            status: r.get(4)?,
            score: r.get::<_, Option<f64>>(5)?.map(|v| v * 100.0),
            measurement_count: r.get(6)?,
            hypothesis_count: r.get(7)?,
        })
    }).map_err(e2s)?;
    rows.collect::<rusqlite::Result<Vec<_>>>().map_err(e2s)
}

/// One run/session with a real capture span, for hours proposals (FS-12 AC-2).
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CaptureSession {
    pub id: String,
    pub session_type: String,
    pub test: Option<String>,
    pub started_at: String,
    pub ended_at: String,
    pub duration_sec: f64,
    /// `live`, `file`, or null for rows saved before capture timing was recorded.
    pub kind: Option<String>,
    pub asset_id: Option<String>,
    pub setup_id: Option<String>,
}

pub const DEFAULT_SESSION_LIMIT: u32 = 500;
pub const MAX_SESSION_LIMIT: u32 = 2000;

/// Sessions whose capture span is longer than zero, oldest first. `since` keeps
/// sessions that started at or after it; `asset_id` keeps sessions recorded with
/// that asset, directly or through their setup's components. Rows saved before
/// capture timing existed have started_at == ended_at and never appear.
pub fn list_capture_sessions(conn: &Connection, since: Option<&str>, asset_id: Option<&str>, limit: Option<u32>) -> Result<Vec<CaptureSession>, String> {
    let since = since.map(str::trim).filter(|s| !s.is_empty());
    if let Some(s) = since {
        if !crate::usage::valid_timestamp(s) {
            return Err(format!("since must be a UTC ISO timestamp, got '{s}'"));
        }
    }
    let asset_id = asset_id.map(str::trim).filter(|s| !s.is_empty());
    let limit = limit.unwrap_or(DEFAULT_SESSION_LIMIT).clamp(1, MAX_SESSION_LIMIT) as i64;
    let mut stmt = conn.prepare(
        "WITH s AS (
           SELECT id, session_type, context_profile, started_at, ended_at, setup_id,
                  CASE WHEN json_valid(config_snapshot_json) THEN config_snapshot_json ELSE '{}' END AS cfg
           FROM session
           WHERE ended_at IS NOT NULL AND julianday(ended_at) > julianday(started_at)
         )
         SELECT id, session_type, context_profile, started_at, ended_at,
                COALESCE(CAST(json_extract(cfg, '$.durationSec') AS REAL), (julianday(ended_at) - julianday(started_at)) * 86400.0),
                json_extract(cfg, '$.captureKind'),
                COALESCE(json_extract(cfg, '$.assetId'), json_extract(cfg, '$.deviceId')),
                setup_id
         FROM s
         WHERE (?1 IS NULL OR julianday(started_at) >= julianday(?1))
           AND (?2 IS NULL OR json_extract(cfg, '$.assetId') = ?2 OR json_extract(cfg, '$.deviceId') = ?2
                OR setup_id IN (SELECT setup_id FROM setup_component WHERE asset_id = ?2))
         ORDER BY julianday(started_at), id LIMIT ?3",
    ).map_err(e2s)?;
    let rows = stmt.query_map(params![since, asset_id, limit], |r| {
        Ok(CaptureSession {
            id: r.get(0)?,
            session_type: r.get(1)?,
            test: r.get(2)?,
            started_at: r.get(3)?,
            ended_at: r.get(4)?,
            duration_sec: (r.get::<_, f64>(5)? * 1000.0).round() / 1000.0,
            kind: r.get(6)?,
            asset_id: r.get(7)?,
            setup_id: r.get(8)?,
        })
    }).map_err(e2s)?;
    rows.collect::<rusqlite::Result<Vec<_>>>().map_err(e2s)
}

/// Full run: session, measurements, and hypotheses with support/contradiction
/// evidence (each entry has evidenceId, weight, summary, measurementIds).
pub fn get_run(conn: &Connection, id: &str) -> Result<Option<Value>, String> {
    let session = conn.query_row(
        "SELECT id, session_type, setup_id, started_at, ended_at, status, context_profile, session_quality, config_snapshot_json FROM session WHERE id = ?1",
        [id],
        |r| {
            let config: String = r.get(8)?;
            Ok(json!({
                "id": r.get::<_, String>(0)?,
                "sessionType": r.get::<_, String>(1)?,
                "setupId": r.get::<_, Option<String>>(2)?,
                "startedAt": r.get::<_, String>(3)?,
                "endedAt": r.get::<_, Option<String>>(4)?,
                "status": r.get::<_, String>(5)?,
                "test": r.get::<_, Option<String>>(6)?,
                "score": r.get::<_, Option<f64>>(7)?.map(|v| v * 100.0),
                "config": serde_json::from_str::<Value>(&config).unwrap_or(Value::Null),
            }))
        },
    );
    let mut session = match session {
        Ok(v) => v,
        Err(rusqlite::Error::QueryReturnedNoRows) => return Ok(None),
        Err(e) => return Err(e2s(e)),
    };

    let mut stmt = conn.prepare(
        "SELECT m.id, m.metric_key, m.state, m.numeric_value, m.text_value, m.unit, m.confidence, m.uncertainty, m.quality_flags_json, am.description FROM measurement m LEFT JOIN analysis_method am ON am.id = m.method_id WHERE m.session_id = ?1 ORDER BY m.metric_key, m.id",
    ).map_err(e2s)?;
    let measurements = stmt.query_map([id], |r| {
        let flags: String = r.get(8)?;
        Ok(json!({
            "id": r.get::<_, String>(0)?,
            "metricId": r.get::<_, String>(1)?,
            "label": r.get::<_, Option<String>>(9)?,
            "origin": r.get::<_, String>(2)?,
            "value": r.get::<_, Option<f64>>(3)?,
            "text": r.get::<_, Option<String>>(4)?,
            "unit": r.get::<_, Option<String>>(5)?,
            "confidence": r.get::<_, Option<f64>>(6)?,
            "uncertainty": r.get::<_, Option<f64>>(7)?,
            "qualityFlags": serde_json::from_str::<Value>(&flags).unwrap_or(json!([])),
        }))
    }).map_err(e2s)?.collect::<rusqlite::Result<Vec<_>>>().map_err(e2s)?;

    let mut hstmt = conn.prepare(
        "SELECT id, hypothesis_key, status, confidence, severity, summary, alternatives_json, isolation_tests_json FROM hypothesis WHERE session_id = ?1 ORDER BY id",
    ).map_err(e2s)?;
    let hyps: Vec<(String, Value)> = hstmt.query_map([id], |r| {
        let alt: String = r.get(6)?;
        let iso: String = r.get(7)?;
        let hid: String = r.get(0)?;
        Ok((hid.clone(), json!({
            "id": hid,
            "key": r.get::<_, String>(1)?,
            "status": r.get::<_, String>(2)?,
            "confidence": r.get::<_, f64>(3)?,
            "severity": r.get::<_, String>(4)?,
            "summary": r.get::<_, String>(5)?,
            "alternatives": serde_json::from_str::<Value>(&alt).unwrap_or(json!([])),
            "isolationTests": serde_json::from_str::<Value>(&iso).unwrap_or(json!([])),
        })))
    }).map_err(e2s)?.collect::<rusqlite::Result<Vec<_>>>().map_err(e2s)?;

    let mut hypotheses = Vec::new();
    for (hid, mut h) in hyps {
        h["support"] = Value::Array(link_rows(conn, "hypothesis_support", &hid)?);
        h["contradictions"] = Value::Array(link_rows(conn, "hypothesis_contradiction", &hid)?);
        hypotheses.push(h);
    }
    session["measurements"] = Value::Array(measurements);
    session["hypotheses"] = Value::Array(hypotheses);
    Ok(Some(session))
}

fn link_rows(conn: &Connection, table: &str, hypothesis_id: &str) -> Result<Vec<Value>, String> {
    // `table` is one of two fixed literals chosen by get_run.
    let table = match table {
        "hypothesis_support" => "hypothesis_support",
        "hypothesis_contradiction" => "hypothesis_contradiction",
        _ => return Err("invalid link table".into()),
    };
    let sql = format!(
        "SELECT l.evidence_id, l.weight, e.summary, e.evidence_type FROM {table} l JOIN evidence e ON e.id = l.evidence_id WHERE l.hypothesis_id = ?1 ORDER BY l.evidence_id"
    );
    let mut stmt = conn.prepare(&sql).map_err(e2s)?;
    let rows = stmt.query_map([hypothesis_id], |r| Ok((r.get::<_, String>(0)?, r.get::<_, f64>(1)?, r.get::<_, String>(2)?, r.get::<_, String>(3)?))).map_err(e2s)?
        .collect::<rusqlite::Result<Vec<_>>>().map_err(e2s)?;
    let mut out = Vec::new();
    for (eid, weight, summary, etype) in rows {
        let mut ms = conn.prepare("SELECT measurement_id FROM evidence_measurement WHERE evidence_id = ?1 ORDER BY measurement_id").map_err(e2s)?;
        let ids = ms.query_map([&eid], |r| r.get::<_, String>(0)).map_err(e2s)?.collect::<rusqlite::Result<Vec<_>>>().map_err(e2s)?;
        out.push(json!({"evidenceId": eid, "weight": weight, "summary": summary, "evidenceType": etype, "measurementIds": ids}));
    }
    Ok(out)
}

// ---- Repeat-scan alignment ----

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ScanInput {
    pub id: Option<String>,
    pub session_id: String,
    /// Existing record_side id; if absent a minimal release/copy/side is created.
    pub record_side_id: Option<String>,
    pub record_title: Option<String>,
    pub side_label: Option<String>,
    pub start_sample: i64,
    pub end_sample: i64,
    pub scan_version: Option<i64>,
    pub condition_score: Option<f64>,
    pub live_readiness: Option<String>,
}

#[derive(Debug, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct EventCounts {
    #[serde(default)]
    pub persistent: i64,
    #[serde(default)]
    pub new: i64,
    #[serde(default)]
    pub missing: i64,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ScanAlignmentInput {
    pub id: Option<String>,
    pub scan_a: ScanInput,
    pub scan_b: ScanInput,
    pub method: Option<String>,
    pub offset_samples: i64,
    pub confidence: f64,
    #[serde(default)]
    pub counts: Option<EventCounts>,
    /// Free-form drift model (e.g. {"ppm": 12.5}); stored with the counts.
    #[serde(default)]
    pub drift: Option<Value>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ScanAlignmentSaved {
    pub id: String,
    pub scan_a_id: String,
    pub scan_b_id: String,
}

fn ensure_side(tx: &rusqlite::Transaction, s: &ScanInput) -> Result<String, String> {
    if let Some(id) = &s.record_side_id {
        return Ok(id.clone());
    }
    let rel = new_id();
    let copy = new_id();
    let side = new_id();
    tx.execute("INSERT INTO record_release (id, title) VALUES (?1, ?2)", params![rel, s.record_title.as_deref().unwrap_or("Untitled record")]).map_err(e2s)?;
    tx.execute("INSERT INTO record_copy (id, record_id) VALUES (?1, ?2)", params![copy, rel]).map_err(e2s)?;
    tx.execute("INSERT INTO record_side (id, record_copy_id, side_label) VALUES (?1, ?2, ?3)", params![side, copy, s.side_label.as_deref().unwrap_or("A")]).map_err(e2s)?;
    Ok(side)
}

fn save_scan(tx: &rusqlite::Transaction, s: &ScanInput, side_id: &str) -> Result<String, String> {
    let id = s.id.clone().unwrap_or_else(new_id);
    tx.execute(
        "INSERT INTO full_side_scan (id, session_id, record_side_id, start_sample, end_sample, scan_version, condition_score, live_readiness, raw_audio_retained) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, 0)
         ON CONFLICT(id) DO UPDATE SET session_id=excluded.session_id, record_side_id=excluded.record_side_id, start_sample=excluded.start_sample, end_sample=excluded.end_sample, scan_version=excluded.scan_version, condition_score=excluded.condition_score, live_readiness=excluded.live_readiness",
        params![id, s.session_id, side_id, s.start_sample, s.end_sample, s.scan_version.unwrap_or(1), s.condition_score, s.live_readiness],
    ).map_err(e2s)?;
    Ok(id)
}

/// Persist two scans and their alignment. Event counts and drift are stored in
/// scan_alignment.drift_model_json as {"counts": {...}, "drift": ...}.
pub fn save_scan_alignment(conn: &mut Connection, input: &ScanAlignmentInput) -> Result<ScanAlignmentSaved, String> {
    if !(0.0..=1.0).contains(&input.confidence) {
        return Err("confidence must be between 0 and 1".into());
    }
    let tx = conn.transaction().map_err(e2s)?;
    let side_a = ensure_side(&tx, &input.scan_a)?;
    // Repeat scans of the same side share a record side unless told otherwise.
    let side_b = match (&input.scan_b.record_side_id, &input.scan_b.record_title) {
        (None, None) => side_a.clone(),
        _ => ensure_side(&tx, &input.scan_b)?,
    };
    let a = save_scan(&tx, &input.scan_a, &side_a)?;
    let b = save_scan(&tx, &input.scan_b, &side_b)?;
    let id = input.id.clone().unwrap_or_else(new_id);
    let counts = input.counts.as_ref().map(|c| json!({"persistent": c.persistent, "new": c.new, "missing": c.missing}));
    let model = json!({"counts": counts, "drift": input.drift}).to_string();
    tx.execute(
        "INSERT INTO scan_alignment (id, scan_a_id, scan_b_id, alignment_method, offset_samples, drift_model_json, confidence) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
         ON CONFLICT(id) DO UPDATE SET scan_a_id=excluded.scan_a_id, scan_b_id=excluded.scan_b_id, alignment_method=excluded.alignment_method, offset_samples=excluded.offset_samples, drift_model_json=excluded.drift_model_json, confidence=excluded.confidence",
        params![id, a, b, input.method.as_deref().unwrap_or("cross_correlation"), input.offset_samples, model, input.confidence],
    ).map_err(e2s)?;
    tx.commit().map_err(e2s)?;
    Ok(ScanAlignmentSaved { id, scan_a_id: a, scan_b_id: b })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn migration_applies_to_memory_database() {
        let conn = Connection::open_in_memory().unwrap();
        apply_migrations(&conn).unwrap();
        let count: i64 = conn.query_row(
            "SELECT COUNT(*) FROM schema_migration WHERE version=1",
            [],
            |r| r.get(0),
        ).unwrap();
        assert_eq!(count, 1);
    }

    #[test]
    fn migrations_apply_in_order_and_are_idempotent() {
        let conn = Connection::open_in_memory().unwrap();
        apply_migrations(&conn).unwrap();
        let versions: Vec<i64> = MIGRATIONS.iter().map(|(v, _)| *v).collect();
        assert!(versions.windows(2).all(|w| w[0] < w[1]), "MIGRATIONS must be sorted by version");
        assert_eq!(applied_migrations(&conn).unwrap(), versions);
        // device library tables exist after 0002
        for t in ["device_profile", "device_test_result", "asset_midi_map"] {
            let n: i64 = conn.query_row("SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name=?1", [t], |r| r.get(0)).unwrap();
            assert_eq!(n, 1, "{t} missing");
        }
        // second run is a no-op
        apply_migrations(&conn).unwrap();
        let rows: i64 = conn.query_row("SELECT COUNT(*) FROM schema_migration WHERE version < 1000", [], |r| r.get(0)).unwrap();
        assert_eq!(rows as usize, MIGRATIONS.len());
    }

    #[test]
    fn upgrades_a_version_1_database_without_losing_data() {
        let conn = Connection::open_in_memory().unwrap();
        // a 0.0.2 database: only 0001 applied
        conn.execute_batch(MIGRATIONS[0].1).unwrap();
        conn.execute("INSERT INTO manufacturer (id, name, created_at, updated_at) VALUES ('m1', 'Keep Me', 'now', 'now')", []).unwrap();
        assert_eq!(applied_migrations(&conn).unwrap(), vec![1]);
        apply_migrations(&conn).unwrap();
        assert_eq!(applied_migrations(&conn).unwrap(), MIGRATIONS.iter().map(|(v, _)| *v).collect::<Vec<_>>());
        let name: String = conn.query_row("SELECT name FROM manufacturer WHERE id='m1'", [], |r| r.get(0)).unwrap();
        assert_eq!(name, "Keep Me");
    }

    #[test]
    fn diagnostic_run_persists_measurement_and_finding() {
        let mut conn = Connection::open_in_memory().unwrap();
        conn.execute_batch("PRAGMA foreign_keys=ON;").unwrap();
        apply_migrations(&conn).unwrap();
        let run = PersistRun {
            id: "run-test".into(),
            device_id: None,
            test: "Stereo balance".into(),
            created_at: "2026-10-06T08:00:00Z".into(),
            source_file: Some("fixture.wav".into()),
            sample_rate: Some(48000),
            channels: Some(2),
            score: Some(92.0),
            measurements: vec![PersistMeasurement {
                metric_id: "channel_balance_db".into(),
                label: Some("Channel balance".into()),
                value: 0.2,
                unit: "dB".into(),
                origin: Some("measured".into()),
                confidence: Some(0.9),
                uncertainty: None,
                quality_flags: Some(vec![]),
            }],
            findings: vec![PersistFinding {
                code: "CHECK".into(),
                title: "Review".into(),
                detail: "Example".into(),
                severity: "review".into(),
                confidence: Some(0.7),
                possible_causes: Some(vec!["cause".into()]),
                isolation_tests: Some(vec!["repeat".into()]),
                ..Default::default()
            }],
            ..Default::default()
        };
        persist_run(&mut conn, &run).unwrap();
        let mc: i64 = conn.query_row(
            "SELECT COUNT(*) FROM measurement WHERE session_id='run-test'",
            [],
            |r| r.get(0),
        ).unwrap();
        let ec: i64 = conn.query_row(
            "SELECT COUNT(*) FROM evidence WHERE session_id='run-test'",
            [],
            |r| r.get(0),
        ).unwrap();
        assert_eq!(mc, 1);
        assert_eq!(ec, 1);
    }

    fn mem() -> Connection {
        let c = Connection::open_in_memory().unwrap();
        c.execute_batch("PRAGMA foreign_keys=ON;").unwrap();
        apply_migrations(&c).unwrap();
        c
    }

    fn meas(id: &str, v: f64) -> PersistMeasurement {
        PersistMeasurement { metric_id: id.into(), label: None, value: v, unit: "dB".into(), origin: None, confidence: Some(0.8), uncertainty: None, quality_flags: None }
    }

    fn graph_run(id: &str, created: &str) -> PersistRun {
        PersistRun {
            id: id.into(),
            test: "Stereo balance".into(),
            created_at: created.into(),
            score: Some(80.0),
            measurements: vec![meas("a", 1.0), meas("b", 2.0), meas("c", 3.0)],
            findings: vec![PersistFinding {
                code: "IMBALANCE".into(),
                title: "t".into(),
                detail: "d".into(),
                severity: "review".into(),
                confidence: Some(0.7),
                alternatives: Some(vec!["cable".into()]),
                supported_by: Some(vec!["a".into(), "b".into(), "missing".into()]),
                contradicted_by: Some(vec!["c".into(), "nope".into()]),
                ..Default::default()
            }],
            ..Default::default()
        }
    }

    #[test]
    fn hypothesis_support_and_contradiction_persist() {
        let mut c = mem();
        persist_run(&mut c, &graph_run("r1", "2026-10-06T08:00:00Z")).unwrap();
        let (status, conf): (String, f64) = c.query_row("SELECT status, confidence FROM hypothesis WHERE session_id='r1'", [], |r| Ok((r.get(0)?, r.get(1)?))).unwrap();
        assert_eq!(status, "contested");
        assert_eq!(conf, 0.7);
        fn n(c: &Connection, sql: &str) -> i64 { c.query_row(sql, [], |r| r.get(0)).unwrap() }
        assert_eq!(n(&c, "SELECT COUNT(*) FROM hypothesis_support"), 1);
        assert_eq!(n(&c, "SELECT COUNT(*) FROM hypothesis_contradiction"), 1);
        assert_eq!(n(&c, "SELECT COUNT(*) FROM evidence_measurement"), 3);
        let stype: String = c.query_row("SELECT session_type FROM session WHERE id='r1'", [], |r| r.get(0)).unwrap();
        assert_eq!(stype, "diagnostic");
        // re-saving the same run is idempotent
        persist_run(&mut c, &graph_run("r1", "2026-10-06T08:00:00Z")).unwrap();
        assert_eq!(n(&c, "SELECT COUNT(*) FROM hypothesis"), 1);
        assert_eq!(n(&c, "SELECT COUNT(*) FROM evidence"), 2);
    }

    #[test]
    fn legacy_payload_without_new_fields_deserializes() {
        let run: PersistRun = serde_json::from_str(r#"{"id":"x","test":"t","createdAt":"2026-01-01","measurements":[],"findings":[{"code":"C","title":"t","detail":"d","severity":"info"}]}"#).unwrap();
        let mut c = mem();
        persist_run(&mut c, &run).unwrap();
        let s: String = c.query_row("SELECT status FROM hypothesis", [], |r| r.get(0)).unwrap();
        assert_eq!(s, "supported");
    }

    #[test]
    fn list_and_get_run() {
        let mut c = mem();
        persist_run(&mut c, &graph_run("r1", "2026-10-06T08:00:00Z")).unwrap();
        persist_run(&mut c, &graph_run("r2", "2026-10-07T08:00:00Z")).unwrap();
        let runs = list_runs(&c, Some(1)).unwrap();
        assert_eq!(runs.len(), 1);
        assert_eq!(runs[0].id, "r2");
        assert_eq!(runs[0].measurement_count, 3);
        assert_eq!(runs[0].hypothesis_count, 1);
        assert_eq!(runs[0].score, Some(80.0));
        assert_eq!(list_runs(&c, None).unwrap().len(), 2);
        let run = get_run(&c, "r1").unwrap().unwrap();
        assert_eq!(run["measurements"].as_array().unwrap().len(), 3);
        // label persisted via analysis_method.description; falls back to the metric id when none was supplied
        assert_eq!(run["measurements"][0]["label"], "a");
        let mut labelled = graph_run("r3", "2026-10-08T08:00:00Z");
        labelled.measurements[0].label = Some("Alpha level".into());
        persist_run(&mut c, &labelled).unwrap();
        let r3 = get_run(&c, "r3").unwrap().unwrap();
        assert_eq!(r3["measurements"][0]["metricId"], "a");
        assert!(r3["measurements"][0]["label"].is_string());
        let h = &run["hypotheses"][0];
        assert_eq!(h["status"], "contested");
        assert_eq!(h["support"][0]["measurementIds"].as_array().unwrap().len(), 2);
        assert_eq!(h["contradictions"][0]["measurementIds"][0], "r1:c");
        assert!(get_run(&c, "none").unwrap().is_none());
    }

    fn timed(id: &str, created: &str) -> PersistRun {
        PersistRun { id: id.into(), test: "DVS signal".into(), created_at: created.into(), ..Default::default() }
    }

    fn span_of(c: &Connection, id: &str) -> (String, Option<String>, String) {
        c.query_row("SELECT started_at, ended_at, config_snapshot_json FROM session WHERE id = ?1", [id], |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?))).unwrap()
    }

    #[test]
    fn legacy_run_keeps_started_equal_to_ended_and_config_unchanged() {
        let mut c = mem();
        persist_run(&mut c, &timed("old", "2026-10-06T08:00:00Z")).unwrap();
        let (s, e, cfg) = span_of(&c, "old");
        assert_eq!((s.as_str(), e.as_deref()), ("2026-10-06T08:00:00Z", Some("2026-10-06T08:00:00Z")));
        let cfg: Value = serde_json::from_str(&cfg).unwrap();
        for k in ["durationSec", "captureKind", "assetId"] {
            assert!(cfg.get(k).is_none(), "{k} must not appear on legacy payloads");
        }
        assert!(list_capture_sessions(&c, None, None, None).unwrap().is_empty(), "zero-length rows are not capture sessions");
    }

    #[test]
    fn run_records_real_capture_start_end_and_duration() {
        let mut c = mem();
        // explicit start and end
        let mut r = timed("live", "2026-10-10T20:40:05.000Z");
        r.started_at = Some("2026-10-10T20:00:00.000Z".into());
        r.ended_at = Some("2026-10-10T20:40:00.000Z".into());
        r.capture_kind = Some("live".into());
        persist_run(&mut c, &r).unwrap();
        let (s, e, cfg) = span_of(&c, "live");
        assert_eq!((s.as_str(), e.as_deref()), ("2026-10-10T20:00:00.000Z", Some("2026-10-10T20:40:00.000Z")));
        let cfg: Value = serde_json::from_str(&cfg).unwrap();
        assert_eq!(cfg["durationSec"], 2400.0);
        assert_eq!(cfg["captureKind"], "live");
        // duration only: ends at createdAt, starts duration earlier
        let mut f = timed("file", "2026-10-10T21:00:00.000Z");
        f.duration_sec = Some(90.5);
        f.capture_kind = Some("file".into());
        persist_run(&mut c, &f).unwrap();
        let (s, e, _) = span_of(&c, "file");
        assert_eq!((s.as_str(), e.as_deref()), ("2026-10-10T20:58:29.500Z", Some("2026-10-10T21:00:00.000Z")));
        // get_run and list_runs expose the real span
        let run = get_run(&c, "live").unwrap().unwrap();
        assert_eq!(run["startedAt"], "2026-10-10T20:00:00.000Z");
        assert_eq!(run["endedAt"], "2026-10-10T20:40:00.000Z");
        let listed = list_runs(&c, None).unwrap();
        assert_eq!(listed.iter().find(|x| x.id == "file").unwrap().ended_at.as_deref(), Some("2026-10-10T21:00:00.000Z"));
    }

    #[test]
    fn capture_timing_is_validated() {
        let mut c = mem();
        let bad = |f: &dyn Fn(&mut PersistRun)| { let mut r = timed("b", "2026-10-10T21:00:00.000Z"); f(&mut r); r };
        let cases: Vec<PersistRun> = vec![
            bad(&|r| r.capture_kind = Some("stream".into())),
            bad(&|r| r.duration_sec = Some(-1.0)),
            bad(&|r| r.duration_sec = Some(f64::NAN)),
            bad(&|r| r.duration_sec = Some(MAX_CAPTURE_SEC + 1.0)),
            bad(&|r| r.started_at = Some("yesterday".into())),
            bad(&|r| r.ended_at = Some("2026-10-10 21:00".into())),
            bad(&|r| { r.started_at = Some("2026-10-10T22:00:00Z".into()); r.ended_at = Some("2026-10-10T21:00:00Z".into()); }),
            bad(&|r| { r.started_at = Some("2026-10-08T21:00:00Z".into()); }),
            bad(&|r| { r.duration_sec = Some(5.0); r.created_at = "2026-10-10".into(); }),
            bad(&|r| r.setup_id = Some("no-such-setup".into())),
        ];
        for (i, r) in cases.iter().enumerate() {
            assert!(persist_run(&mut c, r).is_err(), "case {i} should be rejected");
        }
        let n: i64 = c.query_row("SELECT COUNT(*) FROM session", [], |r| r.get(0)).unwrap();
        assert_eq!(n, 0, "rejected runs leave nothing behind");
    }

    #[test]
    fn capture_sessions_filter_by_since_and_asset_and_setup() {
        let mut c = mem();
        c.execute_batch(
            "INSERT INTO asset (id, nickname, created_at, updated_at) VALUES ('sty','Stylus','t','t'), ('deck','Deck','t','t');
             INSERT INTO setup (id, name, created_at) VALUES ('setup-1','Booth','t');
             INSERT INTO setup_component (id, setup_id, role, asset_id) VALUES ('sc1','setup-1','cartridge','sty');",
        ).unwrap();
        let mk = |id: &str, start: &str, end: &str, asset: Option<&str>, setup: Option<&str>, kind: &str| {
            let mut r = timed(id, end);
            r.started_at = Some(start.into());
            r.ended_at = Some(end.into());
            r.capture_kind = Some(kind.into());
            r.asset_id = asset.map(Into::into);
            r.setup_id = setup.map(Into::into);
            r
        };
        persist_run(&mut c, &mk("a", "2026-10-01T10:00:00.000Z", "2026-10-01T10:40:00.000Z", Some("sty"), None, "live")).unwrap();
        persist_run(&mut c, &mk("b", "2026-10-05T10:00:00.000Z", "2026-10-05T10:20:00.000Z", None, Some("setup-1"), "live")).unwrap();
        persist_run(&mut c, &mk("c", "2026-10-06T10:00:00.000Z", "2026-10-06T10:10:00.000Z", Some("deck"), None, "file")).unwrap();
        let mut legacy_dev = timed("d", "2026-10-07T10:00:00.000Z");
        legacy_dev.device_id = Some("sty".into());
        legacy_dev.duration_sec = Some(60.0);
        persist_run(&mut c, &legacy_dev).unwrap();
        persist_run(&mut c, &timed("old", "2026-10-08T10:00:00Z")).unwrap();

        let ids = |v: Vec<CaptureSession>| v.into_iter().map(|s| s.id).collect::<Vec<_>>();
        assert_eq!(ids(list_capture_sessions(&c, None, None, None).unwrap()), ["a", "b", "c", "d"]);
        assert_eq!(ids(list_capture_sessions(&c, None, Some("sty"), None).unwrap()), ["a", "b", "d"], "direct asset, setup component, deviceId");
        assert_eq!(ids(list_capture_sessions(&c, Some("2026-10-05T10:00:00Z"), Some("sty"), None).unwrap()), ["b", "d"]);
        assert_eq!(ids(list_capture_sessions(&c, None, None, Some(1)).unwrap()), ["a"]);
        let a = &list_capture_sessions(&c, None, Some("sty"), None).unwrap()[0];
        assert_eq!((a.duration_sec, a.kind.as_deref(), a.asset_id.as_deref()), (2400.0, Some("live"), Some("sty")));
        let b = &list_capture_sessions(&c, None, Some("sty"), None).unwrap()[1];
        assert_eq!((b.setup_id.as_deref(), b.asset_id.as_deref()), (Some("setup-1"), None));
        assert!(list_capture_sessions(&c, Some("last week"), None, None).is_err());
        // a malformed config snapshot from elsewhere does not break the listing
        c.execute("INSERT INTO session (id, session_type, started_at, ended_at, app_version, schema_version, status, config_snapshot_json) VALUES ('x','other','2026-10-09T00:00:00Z','2026-10-09T00:01:00Z','0',1,'completed','not json')", []).unwrap();
        let x = list_capture_sessions(&c, Some("2026-10-09T00:00:00Z"), None, None).unwrap();
        assert_eq!((x[0].id.as_str(), x[0].duration_sec, x[0].kind.clone()), ("x", 60.0, None));
    }

    #[test]
    fn capture_session_contract_round_trips() {
        let raw = fs::read_to_string(repo_path("tests/contracts/capture-sessions.json")).unwrap();
        let v: Value = serde_json::from_str(&raw).unwrap();
        let mut c = mem();
        let run: PersistRun = serde_json::from_value(v["save_diagnostic_run"]["request"]["run"].clone()).unwrap();
        persist_run(&mut c, &run).unwrap();
        let req = &v["list_capture_sessions"]["request"];
        let got = list_capture_sessions(&c, req["since"].as_str(), req["assetId"].as_str(), req["limit"].as_u64().map(|n| n as u32)).unwrap();
        assert_eq!(serde_json::to_value(&got).unwrap(), v["list_capture_sessions"]["response"]);
        // FS-12 AC-2: the 40-minute DVS capture is 0.67 h
        assert_eq!((got[0].duration_sec / 3600.0 * 100.0).round() / 100.0, 0.67);
    }

    #[test]
    fn scan_alignment_persists() {
        let mut c = mem();
        persist_run(&mut c, &graph_run("s1", "2026-10-06T08:00:00Z")).unwrap();
        persist_run(&mut c, &graph_run("s2", "2026-10-07T08:00:00Z")).unwrap();
        let input: ScanAlignmentInput = serde_json::from_value(json!({
            "scanA": {"sessionId": "s1", "startSample": 0, "endSample": 1000, "recordTitle": "Test LP"},
            "scanB": {"sessionId": "s2", "startSample": 5, "endSample": 1005},
            "offsetSamples": 5, "confidence": 0.93,
            "counts": {"persistent": 4, "new": 1, "missing": 2},
            "drift": {"ppm": 12.5}
        })).unwrap();
        let saved = save_scan_alignment(&mut c, &input).unwrap();
        let (off, model): (i64, String) = c.query_row("SELECT offset_samples, drift_model_json FROM scan_alignment WHERE id=?1", [&saved.id], |r| Ok((r.get(0)?, r.get(1)?))).unwrap();
        assert_eq!(off, 5);
        let m: Value = serde_json::from_str(&model).unwrap();
        assert_eq!(m["counts"]["missing"], 2);
        assert_eq!(m["drift"]["ppm"], 12.5);
        let sides: i64 = c.query_row("SELECT COUNT(DISTINCT record_side_id) FROM full_side_scan", [], |r| r.get(0)).unwrap();
        assert_eq!(sides, 1);
        let mut bad = input;
        bad.confidence = 2.0;
        assert!(save_scan_alignment(&mut c, &bad).is_err());
    }

    #[test]
    fn new_ids_are_unique_and_uuid_shaped() {
        let a = new_id();
        assert_eq!(a.len(), 36);
        assert_ne!(a, new_id());
    }

    // ---- FS-00 §4.2: build-time migration discovery, transactional runner, fixtures, gate ----

    #[allow(dead_code)]
    mod build_script {
        include!(concat!(env!("CARGO_MANIFEST_DIR"), "/build.rs"));
    }
    use build_script::migration_rules::{parse_migration_name, plan_migrations, transaction_statements};

    fn repo_path(rel: &str) -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("..").join(rel)
    }

    fn names(list: &[&str]) -> Vec<String> {
        list.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn migration_names_must_be_four_digits_and_lower_snake() {
        assert_eq!(parse_migration_name("0001_initial.sql"), Ok(1));
        assert_eq!(parse_migration_name("0021_gear_ledger.sql"), Ok(21));
        assert_eq!(parse_migration_name("9999_a1_b2.sql"), Ok(9999));
        for bad in [
            "001_short.sql", "00001_long.sql", "0003-app_state.sql", "0003_App_State.sql", "0003_.sql",
            "0003_app state.sql", "0003_app-state.sql", "0003.sql", "abcd_x.sql", "0003_app_state.SQL",
            "0000_zero.sql", "٠٠٠٣_x.sql", "0003_é.sql",
        ] {
            assert!(parse_migration_name(bad).is_err(), "{bad} should be rejected");
        }
    }

    #[test]
    fn migration_plan_rejects_duplicates_and_sorts() {
        let plan = plan_migrations(&names(&["0002_b.sql", "README.md", "0001_a.sql", "0010_c.sql"])).unwrap();
        assert_eq!(plan, vec![(1, "0001_a.sql".to_string()), (2, "0002_b.sql".to_string()), (10, "0010_c.sql".to_string())]);
        let err = plan_migrations(&names(&["0004_test_media.sql", "0004_other.sql"])).unwrap_err();
        assert!(err.contains("duplicate migration number 0004"), "{err}");
        assert!(plan_migrations(&names(&["0001_a.sql", "004_b.sql"])).is_err());
    }

    #[test]
    fn transaction_statements_are_detected_at_statement_level_only() {
        for bad in [
            "BEGIN;\nCREATE TABLE t(x);\nCOMMIT;",
            "begin transaction; create table t(x);",
            "CREATE TABLE t(x);\nCOMMIT;",
            "CREATE TABLE t(x); END TRANSACTION;",
            "SAVEPOINT s; RELEASE s;",
            "CREATE TABLE t(x);\nROLLBACK;",
            "BEGIN IMMEDIATE",
        ] {
            assert!(!transaction_statements(bad).is_empty(), "missed: {bad}");
        }
        for ok in [
            "-- BEGIN; COMMIT;\nCREATE TABLE t(x TEXT DEFAULT 'COMMIT; BEGIN');",
            "/* BEGIN; */ CREATE TABLE \"begin\"(x);",
            "CREATE TABLE t(x); CREATE TRIGGER IF NOT EXISTS tr AFTER INSERT ON t BEGIN UPDATE t SET x = CASE WHEN x > 0 THEN 1 ELSE 0 END; SELECT RAISE(ROLLBACK, 'no'); END; CREATE TABLE u(y);",
            "CREATE TEMP TRIGGER tr2 BEFORE DELETE ON t FOR EACH ROW WHEN old.x = 1 BEGIN DELETE FROM u; END;",
            "CREATE TABLE end_marks(begin_at TEXT, commit_id TEXT);",
        ] {
            assert_eq!(transaction_statements(ok), Vec::<String>::new(), "false positive: {ok}");
        }
        assert_eq!(transaction_statements("CREATE TRIGGER t1 AFTER INSERT ON t BEGIN SELECT 1; END; COMMIT;"), vec!["COMMIT".to_string()]);
    }

    #[test]
    fn generated_migrations_match_the_migrations_directory() {
        let mut files: Vec<String> = fs::read_dir(repo_path("database/migrations")).unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
            .collect();
        files.sort();
        let plan = plan_migrations(&files).unwrap();
        let versions: Vec<i64> = plan.iter().map(|(v, _)| *v).collect();
        assert_eq!(MIGRATIONS.iter().map(|(v, _)| *v).collect::<Vec<_>>(), versions, "build.rs output is stale or incomplete");
        for ((version, name), (_, sql)) in plan.iter().zip(MIGRATIONS) {
            let on_disk = fs::read_to_string(repo_path("database/migrations").join(name)).unwrap();
            assert_eq!(&on_disk, sql, "migration {version} content differs from {name}");
            assert_eq!(transaction_statements(sql), Vec::<String>::new(), "{name} must not contain BEGIN/COMMIT");
        }
        assert!(versions.contains(&3), "0003_app_state.sql must be embedded");
    }

    #[test]
    fn version_row_commits_atomically_with_the_migration_sql() {
        let conn = Connection::open_in_memory().unwrap();
        // a non-idempotent migration: re-running it would fail on the duplicate column
        let list: &[(i64, &str)] = &[
            (1, "CREATE TABLE IF NOT EXISTS t (a TEXT);"),
            (2, "CREATE TABLE u (x INTEGER); ALTER TABLE t ADD COLUMN b TEXT;"),
        ];
        let err = apply_migration_list(&conn, list, Some(2)).unwrap_err();
        assert!(err.starts_with("migration 2 failed"), "{err}");
        // failure after the SQL ran: neither the schema change nor the version row persists
        let applied = |c: &Connection| -> Vec<i64> {
            let mut st = c.prepare("SELECT version FROM schema_migration ORDER BY version").unwrap();
            st.query_map([], |r| r.get(0)).unwrap().map(|r| r.unwrap()).collect()
        };
        assert_eq!(applied(&conn), vec![1]);
        let u: i64 = conn.query_row("SELECT COUNT(*) FROM sqlite_master WHERE name = 'u'", [], |r| r.get(0)).unwrap();
        assert_eq!(u, 0);
        assert!(conn.prepare("SELECT b FROM t").is_err());
        assert!(conn.is_autocommit(), "transaction must be closed after a failure");
        // restart: applies once, and further runs never re-execute the ALTER TABLE
        apply_migration_list(&conn, list, None).unwrap();
        assert_eq!(applied(&conn), vec![1, 2]);
        apply_migration_list(&conn, list, None).unwrap();
        apply_migration_list(&conn, list, Some(2)).unwrap();
        assert_eq!(applied(&conn), vec![1, 2]);
        conn.execute("INSERT INTO t (a, b) VALUES ('x', 'y')", []).unwrap();
    }

    #[test]
    fn failing_migration_sql_rolls_back_and_stops_later_migrations() {
        let conn = Connection::open_in_memory().unwrap();
        let list: &[(i64, &str)] = &[
            (1, "CREATE TABLE a (x);"),
            (2, "CREATE TABLE b (x); INSERT INTO missing_table VALUES (1);"),
            (3, "CREATE TABLE c (x);"),
        ];
        assert!(apply_migration_list(&conn, list, None).is_err());
        let tables: i64 = conn.query_row("SELECT COUNT(*) FROM sqlite_master WHERE name IN ('b', 'c')", [], |r| r.get(0)).unwrap();
        assert_eq!(tables, 0);
        assert_eq!(applied_migrations(&conn).unwrap(), vec![1]);
    }

    fn table_names(c: &Connection) -> Vec<String> {
        let mut st = c.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name").unwrap();
        st.query_map([], |r| r.get(0)).unwrap().map(|r| r.unwrap()).collect()
    }

    fn row_counts(c: &Connection) -> Vec<(String, i64)> {
        table_names(c).into_iter().map(|t| {
            let n: i64 = c.query_row(&format!("SELECT COUNT(*) FROM \"{t}\""), [], |r| r.get(0)).unwrap();
            (t, n)
        }).collect()
    }

    fn schema_snapshot(c: &Connection) -> Vec<(String, String, Option<String>)> {
        let mut st = c.prepare("SELECT type, name, sql FROM sqlite_master ORDER BY type, name").unwrap();
        st.query_map([], |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?))).unwrap().map(|r| r.unwrap()).collect()
    }

    fn migration_rows(c: &Connection) -> Vec<(i64, String, Option<String>)> {
        let mut st = c.prepare("SELECT version, applied_at, app_version FROM schema_migration ORDER BY version").unwrap();
        st.query_map([], |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?))).unwrap().map(|r| r.unwrap()).collect()
    }

    fn assert_healthy(c: &Connection, label: &str) {
        let integrity: String = c.query_row("PRAGMA integrity_check", [], |r| r.get(0)).unwrap();
        assert_eq!(integrity, "ok", "{label}: integrity_check");
        let mut st = c.prepare("PRAGMA foreign_key_check").unwrap();
        let violations: Vec<(String, Option<i64>, String)> =
            st.query_map([], |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?))).unwrap().map(|r| r.unwrap()).collect();
        assert!(violations.is_empty(), "{label}: foreign_key_check {violations:?}");
    }

    /// Every committed release fixture, `tests/fixtures/db/v*.sql`, in name order.
    fn fixtures() -> Vec<(String, String)> {
        let dir = repo_path("tests/fixtures/db");
        let mut out: Vec<(String, String)> = fs::read_dir(&dir).unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
            .filter(|n| n.starts_with('v') && n.ends_with(".sql"))
            .map(|n| { let sql = fs::read_to_string(dir.join(&n)).unwrap(); (n, sql) })
            .collect();
        out.sort();
        out
    }

    fn load_fixture(sql: &str) -> Connection {
        let c = Connection::open_in_memory().unwrap();
        c.execute_batch(sql).unwrap();
        c.execute_batch("PRAGMA foreign_keys=ON;").unwrap();
        c
    }

    #[test]
    fn v004_fixture_is_the_shipped_schema_with_rows_in_every_table() {
        let (_, sql) = fixtures().into_iter().find(|(n, _)| n == "v0.04.sql").expect("tests/fixtures/db/v0.04.sql");
        let c = load_fixture(&sql);
        assert_healthy(&c, "v0.04 as loaded");
        assert_eq!(applied_migrations(&c).unwrap(), vec![1, 2], "v0.0.4 shipped migrations 0001+0002");
        // the fixture's schema is exactly what 0001+0002 produce on an empty database
        let fresh = Connection::open_in_memory().unwrap();
        apply_migration_list(&fresh, &MIGRATIONS[..2], None).unwrap();
        let strip = |v: Vec<(String, String, Option<String>)>| v.into_iter().map(|(t, n, _)| (t, n)).collect::<Vec<_>>();
        assert_eq!(strip(schema_snapshot(&c)), strip(schema_snapshot(&fresh)));
        for (table, n) in row_counts(&c) {
            assert!(n > 0, "fixture table {table} has no rows");
        }
        let n = |q: &str| -> i64 { c.query_row(q, [], |r| r.get(0)).unwrap() };
        assert_eq!(n("SELECT COUNT(*) FROM manufacturer"), 2);
        assert_eq!(n("SELECT COUNT(*) FROM product"), 4);
        assert_eq!(n("SELECT COUNT(*) FROM asset"), 3);
        assert_eq!(n("SELECT COUNT(*) FROM asset WHERE nickname LIKE 'My %' AND notes LIKE 'Created from the DeckChek device library.%'"), 1);
        assert_eq!(n("SELECT COUNT(*) FROM session"), 2);
        assert_eq!(n("SELECT COUNT(DISTINCT session_id) FROM capture"), 2);
        assert_eq!(n("SELECT COUNT(DISTINCT session_id) FROM measurement"), 2);
        assert_eq!(n("SELECT COUNT(*) FROM device_profile"), 1);
        assert_eq!(n("SELECT COUNT(*) FROM device_test_result"), 3);
        assert_eq!(n("SELECT COUNT(*) FROM asset_midi_map"), 1);
        assert_eq!(n("SELECT COUNT(*) FROM maintenance_event"), 1);
        assert_eq!(n("SELECT COUNT(*) FROM schema_migration WHERE version = 1000"), 1, "starter-catalog seed marker");
    }

    #[test]
    fn every_release_fixture_upgrades_without_losing_rows() {
        let all = fixtures();
        assert!(all.iter().any(|(n, _)| n == "v0.04.sql"), "v0.04 fixture missing");
        let latest = *MIGRATIONS.iter().map(|(v, _)| v).max().unwrap();
        for (name, sql) in all {
            let c = load_fixture(&sql);
            let before = row_counts(&c);
            let recorded = applied_migrations(&c).unwrap();
            let pending = MIGRATIONS.iter().filter(|(v, _)| !recorded.contains(v)).count() as i64;
            apply_migrations(&c).unwrap_or_else(|e| panic!("{name}: {e}"));
            let after: std::collections::HashMap<String, i64> = row_counts(&c).into_iter().collect();
            for (table, n) in &before {
                let expect = if table == "schema_migration" { *n + pending } else { *n };
                assert_eq!(after.get(table), Some(&expect), "{name}: row count of {table} changed");
            }
            assert_healthy(&c, &name);
            let versions = applied_migrations(&c).unwrap();
            assert_eq!(versions, MIGRATIONS.iter().map(|(v, _)| *v).collect::<Vec<_>>(), "{name}");
            assert_eq!(*versions.last().unwrap(), latest);
            // the pre-existing rows are untouched, not just counted
            if name == "v0.04.sql" {
                let nick: String = c.query_row("SELECT nickname FROM asset WHERE id = 'd7e6f5a4-b3c2-4d1e-8f0a-9b8c7d6e5f4a'", [], |r| r.get(0)).unwrap();
                assert_eq!(nick, "My TWELVE MK2");
                let map: String = c.query_row("SELECT map_json FROM asset_midi_map", [], |r| r.get(0)).unwrap();
                assert!(map.contains("\"mapSource\":\"learned\""));
                assert_eq!(get_run(&c, "run-20260929-1").unwrap().unwrap()["hypotheses"][0]["contradictions"].as_array().unwrap().len(), 1);
            }
            // re-run is a no-op
            let (schema, rows, counts) = (schema_snapshot(&c), migration_rows(&c), row_counts(&c));
            apply_migrations(&c).unwrap();
            assert_eq!(schema_snapshot(&c), schema, "{name}: re-run changed the schema");
            assert_eq!(migration_rows(&c), rows, "{name}: re-run touched schema_migration");
            assert_eq!(row_counts(&c), counts, "{name}: re-run changed rows");
        }
    }

    #[test]
    fn fresh_database_gets_every_migration_and_rerun_is_a_no_op() {
        let c = Connection::open_in_memory().unwrap();
        c.execute_batch("PRAGMA foreign_keys=ON;").unwrap();
        apply_migrations(&c).unwrap();
        assert_eq!(applied_migrations(&c).unwrap(), MIGRATIONS.iter().map(|(v, _)| *v).collect::<Vec<_>>());
        assert!(table_names(&c).contains(&"app_state".to_string()));
        assert_healthy(&c, "fresh");
        let (schema, rows) = (schema_snapshot(&c), migration_rows(&c));
        apply_migrations(&c).unwrap();
        assert_eq!(schema_snapshot(&c), schema);
        assert_eq!(migration_rows(&c), rows);
        // every migration row is stamped with the app version that applied it (0001 self-records as 'spec')
        assert!(rows.iter().filter(|(v, _, _)| *v > 1).all(|(_, _, app)| app.as_deref() == Some(env!("CARGO_PKG_VERSION"))));
    }

    /// Serialises tests that open file databases through the gate.
    static GATE_TESTS: std::sync::Mutex<()> = std::sync::Mutex::new(());

    struct TempDb(PathBuf);
    impl TempDb {
        fn new(tag: &str) -> Self {
            TempDb(std::env::temp_dir().join(format!("deckchek-{tag}-{}-{}.sqlite3", std::process::id(), new_id())))
        }
    }
    impl Drop for TempDb {
        fn drop(&mut self) {
            let _ = fs::remove_file(&self.0);
        }
    }

    #[test]
    fn open_database_upgrades_a_v004_file_without_reseeding() {
        let _serial = GATE_TESTS.lock().unwrap_or_else(PoisonError::into_inner);
        let (_, sql) = fixtures().into_iter().find(|(n, _)| n == "v0.04.sql").unwrap();
        let tmp = TempDb::new("fixture");
        let before = {
            let c = Connection::open(&tmp.0).unwrap();
            c.execute_batch(&sql).unwrap();
            row_counts(&c)
        };
        let conn = open_database(&tmp.0).unwrap();
        let after: std::collections::HashMap<String, i64> = row_counts(&conn).into_iter().collect();
        for (table, n) in &before {
            let expect = if table == "schema_migration" { n + (MIGRATIONS.len() as i64 - 2) } else { *n };
            assert_eq!(after.get(table), Some(&expect), "{table}");
        }
        assert_eq!(after.get("app_state"), Some(&0));
        assert_healthy(&conn, "v0.04 file via open_database");
    }

    #[test]
    fn open_connections_hold_the_gate_read_guard() {
        let _serial = GATE_TESTS.lock().unwrap_or_else(PoisonError::into_inner);
        let tmp = TempDb::new("gate");
        let a = open_database(&tmp.0).unwrap();
        let b = open_database(&tmp.0).unwrap(); // readers share the gate
        assert!(gate().try_write().is_err(), "write guard must wait for open connections");
        drop(a);
        assert!(gate().try_write().is_err());
        drop(b);
        let w = gate().try_write().expect("gate free once every connection is closed");
        drop(w);
        // DbConn derefs to Connection for the existing helpers
        let mut c = open_database(&tmp.0).unwrap();
        persist_run(&mut c, &graph_run("gate-run", "2026-10-10T00:00:00Z")).unwrap();
        assert_eq!(list_runs(&c, None).unwrap().len(), 1);
    }
}
